### ISSUE TITLE
MapTiler key issues

### ISSUE THREAD

**Issue by flacombe** [openinframap/web#38]
Hi all,

We miss background map on OIM since today morning.
I didn't notice this git repository exposes the key used to load MapTiler material. Forking this project defaults people to use the same key elsewhere.

I've requested a new key for projects on my side and sorry if I unfortunately broken anything due to a misuse of the original key.
GitHub may have solution to solve such issues (like gitlab secrets, included in code at build time) as to not include keys and secrets at clone/fork time?

**Comment by russss** [comment]
Don't worry, it's not your fault - my sponsored account with MapTiler has expired and it's been cut off for making too many requests. I think the majority of those are from openinframap itself.

Hopefully MapTiler will restore my account soon. Otherwise I'm going to need to find another source for background vector tiles.

**Comment by russss** [comment]
I've switched to using OpenMapTiles from my own server for the moment.
